name: Post Release PR

on:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Set environment variables
        run: |
          echo "NEW_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          echo "NEW_BRANCH=release-${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          echo "COMMIT_MSG=feat(docs|fw): release EEST $NEW_VERSION" >> $GITHUB_ENV

      - name: Update version in `setup.cfg`
        run: |
          sed -i "s/^version = .*/version = $NEW_VERSION/" setup.cfg
          git add setup.cfg

      - name: Update `CHANGELOG.md`
        env:
          RELEASE_DATE: $(date +'%Y-%m-%d')
        run: |
          # Replace unreleased link with the new release information
          ESCAPED_LINK="https:\/\/github.com\/ethereum\/execution-spec-tests\/releases\/tag\/${NEW_VERSION}"
          RELEASE_NAME=$(gh release view ${NEW_VERSION} --json body -q '.body' | sed -n '1p')
          sed -i "s/## üîú \[Unreleased\](https:\/\/github.com\/ethereum\/execution-spec-tests\/releases\/tag\/version) - 2024-xx-xx/## üîú [${NEW_VERSION}](${ESCAPED_LINK}) - ${RELEASE_DATE}: ${FIRST_LINE}\n\n&/" docs/CHANGELOG.md

          # Append template for the next unreleased section
          sed -i '/\*\*Key:\*\*/r docs/changelog_section_template.md' docs/CHANGELOG.md

          git add docs/CHANGELOG.md


      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.NEW_BRANCH }}
          commit-message: ${{ env.COMMIT_MSG }}
          title: ${{ env.COMMIT_MSG }}
          body: |
            ## üóíÔ∏è Description
            Post ${{ env.NEW_VERSION }} release changes:
            - Bump version within `setup.cfg`.
            - Update `CHANGELOG.md` and copy in `changelog_section_template.md`.
          base: main